spring:
  application:
    name: printermanagement

  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: samuelngari13@gmail.com
    password: amvh hzhi xhco hayu
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: "*"

  # Swagger Configuration
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/openapi-docs

logging:
  level:
    org.springframework.mail: DEBUG
